quarkus:
  http:
    port: 8081
  grpc:
    server:
      use-separate-server: false
  application:
    name: nowchess-io
  smallrye-openapi:
    info-title: NowChess IO Service
    info-version: 1.0.0
    info-description: Chess notation import and export — FEN and PGN
    path: /openapi
  swagger-ui:
    path: /swagger-ui

nowchess:
  internal:
    secret: ${INTERNAL_SECRET:123abc}
