#! /usr/bin/env bash
set -euo pipefail

./gradlew test

if [ "$#" -eq 0 ]; then
  PYTHONUTF8=1 python3 jacoco-reporter/scoverage_coverage_gaps.py
else
  PYTHONUTF8=1 python3 jacoco-reporter/scoverage_coverage_gaps.py "modules/$1/build/reports/scoverageTest/scoverage.xml"
fi
