#! /usr/bin/env bash
set -euo pipefail

./gradlew test

if [ "$#" -eq 0 ]; then
  PYTHONUTF8=1 python3 jacoco-reporter/test_gaps.py
else
  PYTHONUTF8=1 python3 jacoco-reporter/test_gaps.py  --module "$1"
fi
