quarkus:
  http:
    port: 8088
  application:
    name: nowchess-official-bots
  redis:
    hosts: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
  smallrye-jwt:
    enabled: true
  log:
    level: INFO

nowchess:
  redis:
    host: localhost
    port: 6379
    prefix: nowchess

"%deployed":
  nowchess:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      prefix: ${REDIS_PREFIX:nowchess}
