quarkus:
  http:
    port: 8082
  grpc:
    server:
      use-separate-server: false
  application:
    name: rule-service

nowchess:
  internal:
    secret: ${INTERNAL_SECRET:123abc}

"%staging":
  quarkus:
    swagger-ui:
      always-include: true
    dev-ui:
      always-include: true
    log:
      level: INFO

"%production":
  quarkus:
    log:
      level: WARN
