quarkus:
  http:
    port: 8082
    auth:
      permission:
        metrics:
          paths:
            - /q/metrics
            - /q/health/*
          policy: permit
  grpc:
    server:
      use-separate-server: false
  application:
    name: rule-service

nowchess:
  internal:
    secret: ${INTERNAL_SECRET:123abc}

"%deployed":
  quarkus:
    log:
      console:
        json: true
    otel:
      traces:
        sampler: parentbased_traceidratio
        sampler-arg: 0.1
      exporter:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
  nowchess:
    internal:
      secret: ${INTERNAL_SECRET}
